CREATE TABLE aircrafts
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    aircraftuuid UUID                                    NOT NULL,
    airlines_id  BIGINT                                  NOT NULL,
    model        VARCHAR(255)                            NOT NULL,
    total_seats  INTEGER                                 NOT NULL,
    CONSTRAINT pk_aircrafts PRIMARY KEY (id)
);

CREATE TABLE airlines
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    airlineuuid UUID                                    NOT NULL,
    code        VARCHAR(255)                            NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_airlines PRIMARY KEY (id)
);

CREATE TABLE airports
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    airportuuid UUID                                    NOT NULL,
    code        VARCHAR(10)                             NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    city        VARCHAR(255)                            NOT NULL,
    country     VARCHAR(255)                            NOT NULL,
    timezone    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_airports PRIMARY KEY (id)
);

CREATE TABLE flight_schedules
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    flightuuid      UUID                                    NOT NULL,
    flight_number   VARCHAR(255)                            NOT NULL,
    airlines_id     BIGINT                                  NOT NULL,
    aircraft_id     BIGINT                                  NOT NULL,
    route_id        BIGINT                                  NOT NULL,
    departure_time  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    arrival_time    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    available_seats INTEGER                                 NOT NULL,
    base_price      DECIMAL                                 NOT NULL,
    status          VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_flight_schedules PRIMARY KEY (id)
);

CREATE TABLE routes
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    routeuuid          UUID                                    NOT NULL,
    source_airports_id BIGINT,
    destination_id     BIGINT,
    distance           BIGINT                                  NOT NULL,
    CONSTRAINT pk_routes PRIMARY KEY (id)
);

ALTER TABLE aircrafts
    ADD CONSTRAINT uc_aircrafts_aircraftuuid UNIQUE (aircraftuuid);

ALTER TABLE airlines
    ADD CONSTRAINT uc_airlines_airlineuuid UNIQUE (airlineuuid);

ALTER TABLE airlines
    ADD CONSTRAINT uc_airlines_code UNIQUE (code);

ALTER TABLE airports
    ADD CONSTRAINT uc_airports_airportuuid UNIQUE (airportuuid);

ALTER TABLE airports
    ADD CONSTRAINT uc_airports_code UNIQUE (code);

ALTER TABLE flight_schedules
    ADD CONSTRAINT uc_flight_schedules_flightuuid UNIQUE (flightuuid);

ALTER TABLE routes
    ADD CONSTRAINT uc_routes_routeuuid UNIQUE (routeuuid);

ALTER TABLE aircrafts
    ADD CONSTRAINT FK_AIRCRAFTS_ON_AIRLINES FOREIGN KEY (airlines_id) REFERENCES airlines (id);

ALTER TABLE flight_schedules
    ADD CONSTRAINT FK_FLIGHT_SCHEDULES_ON_AIRCRAFT FOREIGN KEY (aircraft_id) REFERENCES aircrafts (id);

ALTER TABLE flight_schedules
    ADD CONSTRAINT FK_FLIGHT_SCHEDULES_ON_AIRLINES FOREIGN KEY (airlines_id) REFERENCES airlines (id);

ALTER TABLE flight_schedules
    ADD CONSTRAINT FK_FLIGHT_SCHEDULES_ON_ROUTE FOREIGN KEY (route_id) REFERENCES routes (id);

ALTER TABLE routes
    ADD CONSTRAINT FK_ROUTES_ON_DESTINATION FOREIGN KEY (destination_id) REFERENCES airports (id);

ALTER TABLE routes
    ADD CONSTRAINT FK_ROUTES_ON_SOURCE_AIRPORTS FOREIGN KEY (source_airports_id) REFERENCES airports (id);